### PR TITLE
fix: update link component to allow modifier+click to properly work, and write tests

### LINKED ISSUE #531: [Bug]: Link leading to other documentation pages aren't opened in a new tab using cmd + click
### Description

Refer to the title

### Expected behaviour

I can open links in a new tab when using cmd + click

### How to reproduce

1. Go to https://tuono.dev/documentation/routing/link-and-navigation
2. (Cmd / ctrl) + Click on a link leading to a page of the documentation site
   - "useRouter API reference page"
   - "Link component API reference page".

### Screenshots

_No response_

### System Info

```shell
Not applicable
```

### System info (Rust)

```shell
Not applicable
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jacobhq**
### Checklist

- [x] I have read [Contributing > Pull requests](https://tuono.dev/documentation/contributing/pull-requests)

### Related issue

Fixes #531

### Overview

This PR makes the link fallback to default `a` behaviour when a modifier key is being pressed.

### CODE REVIEW

**Comment by jacobhq** [comment]
To test in docs, replace tuono version in package.json with `file:../../packages/tuono` after building, then do pnpm install.


https://github.com/user-attachments/assets/293ae844-a72b-417d-aacd-e146b0cd49d8

File: packages/tuono-router/src/components/Link.tsx [hunk 1]
```diff
@@ -42,14 +54,14 @@ export default function Link(
   const handleTransition: React.MouseEventHandler<HTMLAnchorElement> = (
     event,
   ) => {
-    event.preventDefault()
-    onClick?.(event)
-
-    if (href?.startsWith('#')) {
-      window.location.hash = href
```
Comment (Valerioageno) [inline packages/tuono-router/src/components/Link.tsx:49]: Shouldn't we keep this?

**Review by Valerioageno — COMMENTED** [review]
Thanks for this. I think you are on the right track!
I think the time has come for adding also an integration test for the `Link` component. Too many conditions.
Do you mind adding them within this PR? Let me know if you need help

File: packages/tuono-router/src/components/Link.tsx (hunk 1 above)
Comment (jacobhq) [reply packages/tuono-router/src/components/Link.tsx:49]: If we bring it up into the early return block above, we can just let it behave as a normal `a` tag, which I think is better

**Comment by jacobhq** [comment]
> I think the time has come for adding also an integration test for the Link component. Too many conditions.

Agreed, I'm happy to do that!

File: packages/tuono-router/src/components/Link.tsx [hunk 2]
```diff
@@ -42,14 +54,14 @@ export default function Link(
...
+    if (href?.startsWith('#') || isModifiedEvent(event)) {
+      // If the user is pressing a modifier key, we fall back to default behaviour of `a` tag
       return
     }
 
+    event.preventDefault()
+    onClick?.(event)
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.tsx:63]: If a user adds an `onClick` event handler on a `Link` component it won't be called when modifier keys are pressed or the href attribute starts with `#`.
I think that user event handler should be always called.

**Review by marcalexiei — CHANGES_REQUESTED** [review]
Now all links now open in a new tab, with or without modifier key pressed.

This behaviour is caused by the code of `MdxLink`:

https://github.com/tuono-labs/tuono/blob/0f72506f957fe8a36effe788b4e44458ee7c2360/apps/documentation/src/components/MdxProvider/MdxLink/MdxLink.tsx#L34-L38

This issue was hidden by the `event.preventDefault` always executed on `Link` click event handler. 
The `target="_blank"` should be removed from `MdxLink` component when rendering internal links.

File: packages/tuono-router/src/components/Link.tsx (hunk 2 above)
Comment (jacobhq) [reply packages/tuono-router/src/components/Link.tsx]: So if the user passes `onClick` do we still continue? That's what I've just done in latest commit, take a look.

Comment (marcalexiei) [reply packages/tuono-router/src/components/Link.tsx]: For the moment you implementation is fine.
In the future we might consider adding a checking on [defaultPrevented](https://developer.mozilla.org/en-US/docs/Web/API/Event/defaultPrevented) property to allow user to prevent default routing navigation.

**Review by marcalexiei — COMMENTED** [review]
https://github.com/tuono-labs/tuono/pull/534#issuecomment-2645910250

Request a new review once test have been written, thanks.

File: packages/tuono-router/src/components/Link.spec.tsx [hunk 3]
```diff
@@ -0,0 +1,129 @@
...
+
+describe('Link Component', (): void => {
+  beforeEach((): void => {
+    pushMock.mockReset()
+    preloadMock.mockReset()
+    intersectionObserverCallback = undefined
+  })
+
+  it('renders with correct href and text', (): void => {
+    const { getByRole } = render(<Link href="/test">Test Link</Link>)
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.spec.tsx:40]: Do not use matcher from the render method.
Use screen methods from `screen` object exported from testing library:

https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen

File: packages/tuono-router/src/components/Link.spec.tsx [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+    const link = getByRole('link', { name: 'Test Link' })
+
+    expect(link.getAttribute('href')).toBe('/test')
+    expect(link.textContent).toBe('Test Link')
+  })
+
+  it('calls router.push on normal click', (): void => {
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.spec.tsx:47]: Return types are not required in test funtions (remove them in all involved functions ()).

```suggestion
  it('calls router.push on normal click', () => {
```

File: packages/tuono-router/src/components/Link.tsx [hunk 5]
```diff
@@ -42,14 +54,15 @@ export default function Link(
   const handleTransition: React.MouseEventHandler<HTMLAnchorElement> = (
     event,
   ) => {
-    event.preventDefault()
     onClick?.(event)
 
-    if (href?.startsWith('#')) {
-      window.location.hash = href
+    if (href?.startsWith('#') || isModifiedEvent(event)) {
+      // If the user is pressing a modifier key, we fall back to default behaviour of `a` tag
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.tsx:60]:
```suggestion
if (
      href?.startsWith('#') ||
      // If the user is pressing a modifier key, 
      // we fall back to default behaviour of `a` tag
      isModifierKeyPressed(event)
    ) {
```

File: packages/tuono-router/src/components/Link.tsx [hunk 6]
```diff
@@ -18,6 +18,18 @@ interface TuonoLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
   scroll?: boolean
 }
 
+function isModifiedEvent(event: React.MouseEvent): boolean {
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.tsx:21]:
```suggestion
function isModifierKeyPressed(event: React.MouseEvent): boolean {
```

File: packages/tuono-router/src/components/Link.spec.tsx [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+    preloadMock.mockReset()
+    intersectionObserverCallback = undefined
+  })
+
+  it('renders with correct href and text', (): void => {
+    const { getByRole } = render(<Link href="/test">Test Link</Link>)
+    const link = getByRole('link', { name: 'Test Link' })
+
+    expect(link.getAttribute('href')).toBe('/test')
+    expect(link.textContent).toBe('Test Link')
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.spec.tsx:44]: This match is redundant with the `getByRole` parameters.
```suggestion
```

File: packages/tuono-router/src/components/Link.tsx (hunk 6 above)
Comment (jacobhq) [reply packages/tuono-router/src/components/Link.tsx:21]: I think we should keep this name (or change it to something else) since we also check for the target attribute.

Comment (marcalexiei) [reply packages/tuono-router/src/components/Link.tsx:21]: Use `isEventModifierKeyActiveAndTargetDifferentFromSelf`

File: packages/tuono-router/src/components/Link.tsx [hunk 8]
```diff
@@ -18,6 +18,18 @@ interface TuonoLinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
...
+  const eventTarget = event.currentTarget as HTMLAnchorElement | SVGAElement
+  const target = eventTarget.getAttribute('target')
```
Comment (marcalexiei) [inline packages/tuono-router/src/components/Link.tsx:23]:
```suggestion
function isEventModifierKeyActiveAndTargetDifferentFromSelf(
  event: React.MouseEvent<HTMLAnchorElement>,
): boolean {
  const target = event.currentTarget.getAttribute('target')
```

File: packages/tuono-router/src/components/Link.tsx (hunk 6 above)
Comment (jacobhq) [reply packages/tuono-router/src/components/Link.tsx:21]: Ok

**Review by marcalexiei — APPROVED** [review]

File: packages/tuono-router/src/components/Link.spec.tsx (hunk 3 above)
Comment (marcalexiei) [reply packages/tuono-router/src/components/Link.spec.tsx]: #540
