### PR TITLE
fix: broken docs tables

### LINKED ISSUE #360: [Bug]: Broken table on documentation website
### Description

Table component on mobile overflows the viewport. We should make it horizontal scrollable.

Image

Bonus: I'd change the first table header cell from `props` to `args`. I think that props are only the value passed to React components; `router.push` is a function

### Expected behaviour

It should not overflow

### How to reproduce

[Tuono - useRouter](https://tuono.dev/documentation/hooks/use-router)

### Screenshots

_No response_

### System Info

```shell
not required
```

### System info (Rust)

```shell
not required
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jacobhq**
## Context & Description

Fixes #360.

### CODE REVIEW

File: apps/documentation/src/components/MdxProvider/MdxTable/MdxTable.tsx [hunk 1]
```diff
@@ -2,6 +2,8 @@ import type { DetailedHTMLProps, TableHTMLAttributes } from 'react'
 import { Table } from '@mantine/core'
 import type React from 'react'
```
Comment (marcalexiei) [inline apps/documentation/src/components/MdxProvider/MdxTable/MdxTable.tsx:3]: `react` is already imported on line 1. Extract `JSX` from the same import.

**Review by marcalexiei — CHANGES_REQUESTED** [review]
Added some comments.
Please check CI errors.

**Review by Valerioageno — CHANGES_REQUESTED** [review]

**Comment by jacobhq** [comment]
Not sure why CI fails after deleting the file? It runs on my machine.

**Comment by Valerioageno** [comment]
Try rebasing your branch!

**Comment by jacobhq** [comment]
I think it's up to date with main

**Comment by Valerioageno** [comment]
mmmm. I think the best way to overcome this is to update also our documentation website to the latest tuono version `v0.17.1`. 
Probably, the workspace is messing up different versions of the same package.

**Comment by jacobhq** [comment]
Yeah sure :+1:

**Comment by marcalexiei** [comment]
@jacobhq check #363  issue (and add a comment if you want to do the task 😉)

**Review by marcalexiei — APPROVED** [review]
